/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import inti.Dosen;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class menudosendekan extends javax.swing.JFrame {

    /**
     * Creates new form menudosendekan
     */
    int xx, yy;

    public menudosendekan() {
        initComponents();
        npp.setBackground(new java.awt.Color(0, 0, 0, 1));
        nama.setBackground(new java.awt.Color(0, 0, 0, 1));
        ttl.setBackground(new java.awt.Color(0, 0, 0, 1));
        jk.setBackground(new java.awt.Color(0, 0, 0, 1));
        alamat.setBackground(new java.awt.Color(0, 0, 0, 1));
        email.setBackground(new java.awt.Color(0, 0, 0, 1));
        Dosen ds = new Dosen("21833020");
        npp.setText(ds.getNpp());
        nama.setText(ds.getNamaDosen());
        ttl.setText(ds.getTtlDosen());
        jk.setText(ds.getJkDosen());
        agama.setSelectedItem(ds.getAgamaDosen());
        alamat.setText(ds.getAlamatDosen());
        email.setText(ds.getEmailDosen());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        npp = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        ttl = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        agama = new javax.swing.JComboBox<>();
        simpandata = new javax.swing.JLabel();
        backmenu = new javax.swing.JLabel();
        m_dekan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        npp.setEditable(false);
        npp.setBorder(null);
        getContentPane().add(npp, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 170, 30));

        nama.setEditable(false);
        nama.setBorder(null);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 180, 20));

        ttl.setEditable(false);
        ttl.setBorder(null);
        getContentPane().add(ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 180, 30));

        jk.setEditable(false);
        jk.setBorder(null);
        getContentPane().add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 180, 30));

        alamat.setBorder(null);
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 180, 30));

        email.setBorder(null);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 180, 30));

        agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Budha", "Hindu", "Konghucu", "Custom" }));
        getContentPane().add(agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 160, -1));

        simpandata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpandata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpandataMouseClicked(evt);
            }
        });
        getContentPane().add(simpandata, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 150, 30));

        backmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });
        getContentPane().add(backmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 140, 30));

        m_dekan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_image/menu-dosen.png"))); // NOI18N
        getContentPane().add(m_dekan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpandataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpandataMouseClicked
        Dosen ds = new Dosen();
        if (alamat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh kosong");
            alamat.requestFocus();
        } else if (email.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh kosong");
            email.requestFocus();
        } else {
            ds.setAgamaDosen(agama.getSelectedItem().toString());
            ds.setAlamatDosen(alamat.getText());
            ds.setEmailDosen(email.getText());
            ds.setNpp(npp.getText());
            int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Memperbarui Data diri?", null, JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    ds.update();
                } catch (Exception ex) {
                    System.out.println("Error Terletak Pada : " + ex);
                }
            } else if (dialogResult == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Anda telah membatalkan Input data");
            }
        }
    }//GEN-LAST:event_simpandataMouseClicked

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked
        menu_dekan menu = new menu_dekan();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backmenuMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menudosendekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menudosendekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menudosendekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menudosendekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menudosendekan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agama;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel backmenu;
    private javax.swing.JTextField email;
    private javax.swing.JTextField jk;
    private javax.swing.JLabel m_dekan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField npp;
    private javax.swing.JLabel simpandata;
    private javax.swing.JTextField ttl;
    // End of variables declaration//GEN-END:variables
}
