/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import inti.Jabatan;
import inti.Koneksi;
import inti.Proker;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class menuprokerdekan extends javax.swing.JFrame {

    /**
     * Creates new form menuprokerwadek
     */
    int xx,yy;
    public menuprokerdekan() {
        initComponents();
        id.setBackground(new java.awt.Color(0, 0, 0, 1));
        periode.setBackground(new java.awt.Color(0, 0, 0, 1));
        Proker s = new Proker();
        Jabatan p = new Jabatan();
        DefaultTableModel modelTable = (DefaultTableModel) view.getModel();
        modelTable.setRowCount(0);
        p.getproker();
        Object[] info = new Object[10];
        try {
            Iterator it = p.getIteratorProker();
            while (it.hasNext()) {
                s = (Proker) it.next();
                info[0] = s.getIdproker();
                info[1] = s.getDosenPenanggung();
                info[2] = s.getUraianProker();
                info[3] = s.getPeriodeProker();
                info[4] = s.getRevisiProker();
                info[5] = s.getStatusWadek();
                info[6] = s.getStatusdekan();
                info[7] = s.getAnggaranDana();
                info[8] = s.getTglperencanaan();
                modelTable.addRow(info);
            }
            view.setModel(modelTable);
        } catch (Exception ex) {
            System.out.println("Error Terletak Pada Ini : " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        cari = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();
        uraian = new javax.swing.JScrollPane();
        uraianprkr = new javax.swing.JTextArea();
        periode = new javax.swing.JTextField();
        simpandata = new javax.swing.JLabel();
        backtomenu = new javax.swing.JLabel();
        caridata = new javax.swing.JLabel();
        exportdata = new javax.swing.JLabel();
        m_dekan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setBorder(null);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 50, 20));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disetujui", "Tidak Disetujui", " " }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 170, 30));

        cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015/2016", "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021" }));
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 110, 30));

        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dosen Penanggung", "Uraian", "Periode", "Revisi", "Status Wadek", "Status  Dekan", "Anggaran Dana", "Tanggal Perencanaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(view);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 640, 260));

        uraianprkr.setEditable(false);
        uraianprkr.setColumns(20);
        uraianprkr.setRows(5);
        uraian.setViewportView(uraianprkr);

        getContentPane().add(uraian, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 170, 70));

        periode.setEditable(false);
        periode.setBorder(null);
        getContentPane().add(periode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 160, 30));

        simpandata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpandata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpandataMouseClicked(evt);
            }
        });
        getContentPane().add(simpandata, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 160, 40));

        backtomenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtomenuMouseClicked(evt);
            }
        });
        getContentPane().add(backtomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 140, 30));

        caridata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        caridata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caridataMouseClicked(evt);
            }
        });
        getContentPane().add(caridata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 90, 150, 30));

        exportdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exportdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportdataMouseClicked(evt);
            }
        });
        getContentPane().add(exportdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 140, 30));

        m_dekan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_image/proker-dekan.png"))); // NOI18N
        getContentPane().add(m_dekan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpandataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpandataMouseClicked
        Proker p = new Proker();
        if (id.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh kosong");
            id.requestFocus();
        } else if (uraianprkr.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh kosong");
            uraianprkr.requestFocus();
        } else if (status.getSelectedItem().toString().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh kosong");
            uraianprkr.requestFocus();
        } else {
            p.setIdproker(id.getText());
            p.setUraianProker(uraianprkr.getText());
            p.setStatusdekan(status.getSelectedItem().toString());

            int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Memperbarui Data ?", null, JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    p.updatedekan();
                } catch (Exception ex) {
                    System.out.println("Error Terletak Pada : " + ex);
                }
            } else if (dialogResult == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Anda telah membatalkan Input data");
            }
        }
        Proker s = new Proker();
        DefaultTableModel modelTable = (DefaultTableModel) view.getModel();
        modelTable.setRowCount(0);
        Object[] info = new Object[10];
        try {
            ArrayList prokerall = s.viewAll(); //harus dikasih try catch
            Iterator it = prokerall.iterator();
            System.out.println("size: " + prokerall.size()); //ok
            while (it.hasNext()) {
                s = (Proker) it.next();
                info[0] = s.getIdproker();
                info[1] = s.getDosenPenanggung();
                info[2] = s.getUraianProker();
                info[3] = s.getPeriodeProker();
                info[4] = s.getRevisiProker();
                info[5] = s.getStatusWadek();
                info[6] = s.getStatusdekan();
                info[7] = s.getAnggaranDana();
                info[8] = s.getTglperencanaan();
                modelTable.addRow(info);
            }
            view.setModel(modelTable);
        } catch (Exception ex) {
            System.out.println("Error Terletak Pada Ini : " + ex);
        }
    }//GEN-LAST:event_simpandataMouseClicked

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        DefaultTableModel model = (DefaultTableModel) view.getModel();
        int row = view.getSelectedRow();
        id.setText(model.getValueAt(row, 0).toString());
        uraianprkr.setText(model.getValueAt(row, 2).toString());
        periode.setText(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_viewMouseClicked

    private void backtomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtomenuMouseClicked
        menu_dekan md = new menu_dekan();
        md.setVisible(true);
        md.pack();
        md.setLocationRelativeTo(null);
        md.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backtomenuMouseClicked

    private void caridataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caridataMouseClicked
        Proker p = new Proker();
        DefaultTableModel tb = (DefaultTableModel) view.getModel();
        tb.setRowCount(0);
        try {
            p.viewAllfilter(tb, cari.getSelectedItem().toString());
        } catch (Exception ex) {
            Logger.getLogger(menuprokerwakildekan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_caridataMouseClicked

    private void exportdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportdataMouseClicked
        Proker p = new Proker();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Mengexport Data ?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                p.export();
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } else if (dialogResult == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Silahkan Menginputkan Data Lagi");
        } else if (dialogResult == JOptionPane.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "Anda Membatalkan Input Data");
        }


    }//GEN-LAST:event_exportdataMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprokerdekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprokerdekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprokerdekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprokerdekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprokerdekan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backtomenu;
    private javax.swing.JComboBox<String> cari;
    private javax.swing.JLabel caridata;
    private javax.swing.JLabel exportdata;
    private javax.swing.JTextField id;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel m_dekan;
    private javax.swing.JTextField periode;
    private javax.swing.JLabel simpandata;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JScrollPane uraian;
    private javax.swing.JTextArea uraianprkr;
    public javax.swing.JTable view;
    // End of variables declaration//GEN-END:variables
}
