/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import inti.Jabatan;
import inti.RiwayatJabatan;
import javax.swing.JFrame;

/**
 *
 * @author Lenovo
 */
public class menujabatandekan extends javax.swing.JFrame {

    /**
     * Creates new form menujabatandekan
     */
    int xx, yy;

    public menujabatandekan() {
        initComponents();
        npp.setBackground(new java.awt.Color(0, 0, 0, 1));
        nama.setBackground(new java.awt.Color(0, 0, 0, 1));
        masa.setBackground(new java.awt.Color(0, 0, 0, 1));
        awal.setBackground(new java.awt.Color(0, 0, 0, 1));
        akhir.setBackground(new java.awt.Color(0, 0, 0, 1));
        jabatan.setBackground(new java.awt.Color(0, 0, 0, 1));
        Jabatan jt = new Jabatan("22833020");
        RiwayatJabatan ry = new RiwayatJabatan("22833020");
        npp.setText(jt.getNidn());
        nama.setText(ry.getNamaJabatan());
        masa.setText(ry.getStatusJabatan());
        awal.setText(jt.getawal());
        akhir.setText(jt.getakhir());
        jabatan.setText(ry.getMasaJabatan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        npp = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        riwayatdata = new javax.swing.JLabel();
        backtomenu = new javax.swing.JLabel();
        jabatan = new javax.swing.JTextField();
        masa = new javax.swing.JTextField();
        awal = new javax.swing.JTextField();
        akhir = new javax.swing.JTextField();
        m_dekan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        npp.setEditable(false);
        npp.setBorder(null);
        getContentPane().add(npp, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 150, 20));

        nama.setEditable(false);
        nama.setBorder(null);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 160, 30));

        riwayatdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayatdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatdataMouseClicked(evt);
            }
        });
        getContentPane().add(riwayatdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 150, 40));

        backtomenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtomenuMouseClicked(evt);
            }
        });
        getContentPane().add(backtomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 150, 40));

        jabatan.setEditable(false);
        jabatan.setBorder(null);
        getContentPane().add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 140, 20));

        masa.setEditable(false);
        masa.setBorder(null);
        getContentPane().add(masa, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 150, 20));

        awal.setEditable(false);
        awal.setBorder(null);
        getContentPane().add(awal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 170, 30));

        akhir.setEditable(false);
        akhir.setBorder(null);
        getContentPane().add(akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 170, 30));

        m_dekan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_image/Menu-jabatan.png"))); // NOI18N
        getContentPane().add(m_dekan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void riwayatdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatdataMouseClicked
        riwayatdekan rt = new riwayatdekan();
        rt.setVisible(true);
        rt.pack();
        rt.setLocationRelativeTo(null);
        rt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_riwayatdataMouseClicked

    private void backtomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtomenuMouseClicked
        menu_dekan menu = new menu_dekan();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backtomenuMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menujabatandekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menujabatandekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menujabatandekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menujabatandekan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menujabatandekan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField akhir;
    private javax.swing.JTextField awal;
    private javax.swing.JLabel backtomenu;
    private javax.swing.JTextField jabatan;
    private javax.swing.JLabel m_dekan;
    private javax.swing.JTextField masa;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField npp;
    private javax.swing.JLabel riwayatdata;
    // End of variables declaration//GEN-END:variables
}
