/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import inti.Dosen;
import inti.Jabatan;
import inti.RiwayatJabatan;
import javax.swing.JFrame;

/**
 *
 * @author Lenovo
 */
public class menujabatankaprodi extends javax.swing.JFrame {

    /**
     * Creates new form menujabatankaprodi
     */
    int xx, yy;

    public menujabatankaprodi() {
        initComponents();
        npp.setBackground(new java.awt.Color(0, 0, 0, 1));
        namajabatan.setBackground(new java.awt.Color(0, 0, 0, 1));
        masajabatan.setBackground(new java.awt.Color(0, 0, 0, 1));
        awal.setBackground(new java.awt.Color(0, 0, 0, 1));
        akhir.setBackground(new java.awt.Color(0, 0, 0, 1));
        status.setBackground(new java.awt.Color(0, 0, 0, 1));
        Jabatan jt = new Jabatan("22833019");
        RiwayatJabatan ry = new RiwayatJabatan("22833019");
        npp.setText(jt.getNidn());
        namajabatan.setText(ry.getNamaJabatan());
        awal.setText(jt.getawal());
        akhir.setText(jt.getakhir());
        status.setText(ry.getStatusJabatan());
        masajabatan.setText(ry.getMasaJabatan());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        npp = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        namajabatan = new javax.swing.JTextField();
        masajabatan = new javax.swing.JTextField();
        riwayatdata = new javax.swing.JLabel();
        backtomenu = new javax.swing.JLabel();
        awal = new javax.swing.JTextField();
        akhir = new javax.swing.JTextField();
        m_kaprodi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        npp.setEditable(false);
        npp.setBorder(null);
        getContentPane().add(npp, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 160, 20));

        status.setEditable(false);
        status.setBorder(null);
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 160, 20));

        namajabatan.setEditable(false);
        namajabatan.setBorder(null);
        getContentPane().add(namajabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 160, 30));

        masajabatan.setEditable(false);
        masajabatan.setBorder(null);
        getContentPane().add(masajabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 160, 20));

        riwayatdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayatdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatdataMouseClicked(evt);
            }
        });
        getContentPane().add(riwayatdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 150, 40));

        backtomenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtomenuMouseClicked(evt);
            }
        });
        getContentPane().add(backtomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 140, 40));

        awal.setEditable(false);
        awal.setBorder(null);
        getContentPane().add(awal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 160, 30));

        akhir.setEditable(false);
        akhir.setBorder(null);
        getContentPane().add(akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 160, 20));

        m_kaprodi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_image/Menu-jabatan.png"))); // NOI18N
        getContentPane().add(m_kaprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void riwayatdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatdataMouseClicked
        riwayatkaprodi rt = new riwayatkaprodi();
        rt.setVisible(true);
        rt.pack();
        rt.setLocationRelativeTo(null);
        rt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_riwayatdataMouseClicked

    private void backtomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtomenuMouseClicked
        menu_kaprodi menu = new menu_kaprodi();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backtomenuMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menujabatankaprodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menujabatankaprodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menujabatankaprodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menujabatankaprodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menujabatankaprodi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField akhir;
    private javax.swing.JTextField awal;
    private javax.swing.JLabel backtomenu;
    private javax.swing.JLabel m_kaprodi;
    private javax.swing.JTextField masajabatan;
    private javax.swing.JTextField namajabatan;
    private javax.swing.JTextField npp;
    private javax.swing.JLabel riwayatdata;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
